# KMCS Markdown Report
# ====================
#
# Documentation-friendly rendering of KMCS findings.
#
# This reporter serialises the reporting layer's canonical data model
# into GitHub-flavored Markdown. Where the HTML reporter produces a
# self-contained visual document and the JSON reporter produces a
# machine-readable interchange document, the Markdown reporter
# produces text that reads as well in a terminal as it does rendered
# on GitHub, in a wiki, or inside a research notebook.
#
# The design goals are:
#
#   * **Readable raw.** The output must be legible when viewed with
#     ``cat``, ``less``, or a plain text editor. Headings, tables,
#     lists, and fenced code blocks carry the structure; no raw HTML
#     is required to understand the document.
#
#   * **Readable rendered.** The same output must render cleanly on
#     GitHub, GitLab, Gitea, and any CommonMark-compliant renderer.
#     Tables use GFM syntax, collapsible sections use ``<details>``
#     (universally supported by these platforms), and code blocks
#     choose their fence length dynamically so that content
#     containing backticks never breaks out of its fence.
#
#   * **Faithful to the data model.** This reporter shares the same
#     :class:`ReportBundle` and :class:`ReportFinding` types that the
#     HTML and JSON reporters consume. It does not re-derive any
#     field from raw subsystem records; if the bundle does not carry
#     a value, the reporter writes "not available" — never a
#     fabricated default.
#
#   * **Stable.** Given the same bundle, the reporter produces
#     byte-identical output. Findings are ordered by severity (most
#     severe first) and then by discovery time (newest first). Table
#     rows, metadata keys, and the table of contents are all emitted
#     in a deterministic order.
#
#   * **Safe.** Every user-supplied string is escaped before being
#     written into a table cell, a heading, or a paragraph.
#     Pipe characters are escaped so they cannot break a table;
#     newlines inside cells become ``<br>``; the fence length of
#     every code block is chosen so that embedded backtick runs
#     cannot close the block early.
#
# Relationship to other reporters
# -------------------------------
#
# :mod:`kmcs.reporting.html` defines the shared data model and the
# factory functions that project analysis, reproduction, and
# regression records onto that model. This module imports those types
# and factories and does not redefine them. The result is that a
# change to how a finding is projected from a crash record affects
# all three reporters identically.
#
# What this module does not do
# ----------------------------
#
#   * It does not run the crash parser, the classifier, the severity
#     assigner, or the fingerprint extractor.
#
#   * It does not compute severity, coverage, or counts that were not
#     already present in the bundle.
#
#   * It does not modify its input. The bundle is read-only.
#
#   * It does not generate HTML. Where a Markdown-specific rendering
#     of a value is required (for example, a collapsible evidence
#     section), the reporter emits the minimum HTML necessary and
#     documents the choice inline.
#
# Document structure
# ------------------
#
# A typical rendered document has the following shape::
#
#     # Report title
#
#     *Subtitle*
#
#     <metadata table>
#
#     ---
#
#     ## Table of contents
#
#     - [Summary](#summary)
#     - [Campaign](#campaign)
#     - [Corpus](#corpus)
#     - [Findings](#findings)
#
#     ---
#
#     ## Summary
#
#     <counts table>
#
#     ---
#
#     ## Campaign
#
#     <campaign table>
#
#     ---
#
#     ## Corpus
#
#     <corpus table>
#
#     ---
#
#     ## Findings
#
#     ### Overview
#
#     <findings summary table>
#
#     ### [Critical] heap-buffer-overflow in parse_header
#
#     <finding detail sections>
#
#     ---
#
#     <supplemental sections>
#
#     ---
#
#     <report data (JSON) in a collapsible block>
#
#     ---
#
#     *Generated by KMCS 1.0.0 at 2026-01-01T00:00:00+00:00*
#
# Compatibility
# -------------
#
# Python 3.10+.

from __future__ import annotations

import hashlib
import json
import logging
import os
import re
import tempfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import (
    Any,
    Callable,
    Dict,
    FrozenSet,
    Iterable,
    List,
    Mapping,
    Optional,
    Sequence,
    TextIO,
    Tuple,
    Union,
)


# ---------------------------------------------------------------------------
# Shared model import
# ---------------------------------------------------------------------------
#
# The reporting layer has exactly one data model, defined in
# kmcs.reporting.html. This reporter consumes that model rather than
# defining its own, so that findings rendered as Markdown, as JSON,
# and as HTML all describe the same object. If the shared model is
# not importable, the reporting layer is not usable as a whole; the
# import error propagates with a clear message.

try:
    from .html import (
        ReportBundle,
        ReportFinding,
        ReportMetadata,
        ReportCampaignSummary,
        ReportCorpusSummary,
        SeverityLevel,
        ReportTheme,
        finding_from_crash,
        finding_from_reproduction,
        finding_from_regression_case,
        GENERATOR_NAME,
        GENERATOR_VERSION,
        DEFAULT_TITLE,
    )
except ImportError as _import_exc:  # pragma: no cover - depends on layout
    raise ImportError(
        "kmcs.reporting.markdown requires kmcs.reporting.html to be "
        f"importable: {_import_exc}"
    ) from _import_exc


logger = logging.getLogger(__name__)


__all__ = [
    "MarkdownReporter",
    "MarkdownOptions",
    "MarkdownError",
    "MarkdownValidationError",
    "MarkdownSerializationError",
    "dump_markdown",
    "dump_markdown_string",
    "render_markdown",
    "write_markdown",
    "describe_format",
    "DEFAULT_FENCE",
    "DEFAULT_FENCE_CHAR",
    "DEFAULT_MAX_OUTPUT_CHARS",
    "DEFAULT_INCLUDE_TOC",
    "DEFAULT_INCLUDE_SUMMARY",
    "DEFAULT_INCLUDE_METADATA_JSON",
    "DEFAULT_USE_DETAILS_BLOCKS",
    "DEFAULT_TRAILING_NEWLINE",
]


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: Default fence character for code blocks. Backticks are the
#: conventional choice and are recognised by every Markdown renderer
#: in common use. When the content of a block contains a run of
#: backticks, the reporter lengthens the fence rather than switching
#: characters, which is the behaviour specified by CommonMark.
DEFAULT_FENCE_CHAR: str = "`"

#: Minimum fence length. CommonMark requires at least three.
DEFAULT_FENCE: str = DEFAULT_FENCE_CHAR * 3

#: Default cap on the number of characters of raw crash output
#: rendered inline. Longer output is truncated and a marker is
#: appended. ``None`` disables the cap.
DEFAULT_MAX_OUTPUT_CHARS: Optional[int] = 40_000

#: Whether the table of contents is emitted by default.
DEFAULT_INCLUDE_TOC: bool = True

#: Whether the summary section is emitted by default.
DEFAULT_INCLUDE_SUMMARY: bool = True

#: Whether the underlying bundle is dumped as JSON in a collapsible
#: block at the end of the report.
DEFAULT_INCLUDE_METADATA_JSON: bool = True

#: Whether verbose content (raw output, metadata JSON, supplemental
#: bodies) is wrapped in ``<details>`` blocks. Disabling this produces
#: a flatter document that is easier to read in a terminal but
#: potentially very long.
DEFAULT_USE_DETAILS_BLOCKS: bool = True

#: Whether a trailing newline is appended to the rendered document.
DEFAULT_TRAILING_NEWLINE: bool = True

#: Placeholder rendered when a field is absent from the bundle. This
#: is intentionally italicised so that it is visually distinct from
#: values that happen to be short strings.
_NOT_AVAILABLE: str = "_not available_"

#: Severity ordering used when sorting findings. Lower numbers are
#: considered more severe.
_SEVERITY_ORDER: Mapping[str, int] = {
    "critical": 0,
    "high": 1,
    "medium": 2,
    "low": 3,
    "informational": 4,
    "unknown": 5,
}

#: Canonical names of the levels in :class:`SeverityLevel`. Kept as a
#: tuple so that iteration order is stable across Python versions.
_SEVERITY_LEVELS: Tuple[str, ...] = (
    "critical",
    "high",
    "medium",
    "low",
    "informational",
    "unknown",
)


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class MarkdownError(Exception):
    """Base class for all Markdown reporter errors."""


class MarkdownValidationError(MarkdownError):
    """Raised when a bundle fails pre-render validation.

    Validation is limited to conditions that would produce a
    malformed document: missing title, findings with no identifier,
    duplicate finding identifiers.
    """


class MarkdownSerializationError(MarkdownError):
    """Raised when a value in the bundle cannot be rendered.

    In practice this exception is rare: the reporter is deliberately
    permissive about the shapes of values it accepts. It is raised
    only when a value cannot be coerced to text at all.
    """


# ---------------------------------------------------------------------------
# Options
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class MarkdownOptions:
    """Immutable options for :class:`MarkdownReporter`.

    Attributes
    ----------
    include_toc:
        When True (default), emit a table of contents after the
        header.
    include_summary:
        When True (default), emit a summary section with derived
        counts.
    include_metadata_json:
        When True (default), emit the underlying bundle as pretty-
        printed JSON inside a collapsible block at the end of the
        report.
    include_raw_output:
        When True (default), include each finding's raw crash output
        inside a collapsible block.
    use_details_blocks:
        When True (default), wrap verbose content in ``<details>``
        blocks. GitHub, GitLab, and Gitea render these as native
        collapsible sections.
    max_output_chars:
        Per-finding cap on the number of characters of raw output
        included. ``None`` disables the cap.
    trailing_newline:
        When True (default), append a single newline to the end of
        the rendered document.
    fence_char:
        Character used for fenced code blocks. Defaults to a
        backtick. Overriding this is rarely necessary; it exists for
        callers that target a non-CommonMark renderer.
    max_table_cell_length:
        Optional cap on the length of a single table cell. Longer
        values are truncated. ``None`` disables the cap. This is
        useful when rendering into terminals with narrow widths.
    """

    include_toc: bool = DEFAULT_INCLUDE_TOC
    include_summary: bool = DEFAULT_INCLUDE_SUMMARY
    include_metadata_json: bool = DEFAULT_INCLUDE_METADATA_JSON
    include_raw_output: bool = True
    use_details_blocks: bool = DEFAULT_USE_DETAILS_BLOCKS
    max_output_chars: Optional[int] = DEFAULT_MAX_OUTPUT_CHARS
    trailing_newline: bool = DEFAULT_TRAILING_NEWLINE
    fence_char: str = DEFAULT_FENCE_CHAR
    max_table_cell_length: Optional[int] = None

    def __post_init__(self) -> None:
        if self.max_output_chars is not None and self.max_output_chars < 0:
            raise ValueError("max_output_chars must be non-negative or None")
        if self.max_table_cell_length is not None and self.max_table_cell_length < 0:
            raise ValueError(
                "max_table_cell_length must be non-negative or None"
            )
        if not self.fence_char:
            raise ValueError("fence_char must not be empty")
        if len(self.fence_char) != 1:
            raise ValueError("fence_char must be a single character")


# ---------------------------------------------------------------------------
# Escaping helpers
# ---------------------------------------------------------------------------


_BACKTICK_RUN_RE = re.compile(r"`+")


def _max_backtick_run(text: str) -> int:
    """Return the length of the longest backtick run in ``text``.

    Returns zero when the text contains no backticks.
    """
    longest = 0
    for match in _BACKTICK_RUN_RE.finditer(text):
        length = match.end() - match.start()
        if length > longest:
            longest = length
    return longest


def _escape_text(value: Any) -> str:
    """Escape a value for inclusion in a Markdown paragraph.

    The escaping is intentionally minimal: Markdown paragraphs are
    forgiving, and over-escaping produces ugly output. The function
    only escapes characters that could change paragraph structure:
    leading ``#``, leading ``-`` followed by a space, leading ``>``,
    and leading digits followed by a period (ordered-list syntax).
    """
    if value is None:
        return _NOT_AVAILABLE
    if isinstance(value, (list, tuple, set, frozenset)):
        if not value:
            return _NOT_AVAILABLE
        return ", ".join(_escape_text(v) for v in value)
    text = str(value)
    if not text:
        return ""
    # Collapse newlines to spaces so that a multi-line value does not
    # accidentally become a multi-line paragraph with its own
    # structure.
    text = text.replace("\r\n", " ").replace("\r", " ").replace("\n", " ")
    # Escape structural prefixes.
    stripped = text.lstrip()
    if stripped.startswith("#"):
        text = "\\" + text.lstrip()
    elif stripped.startswith(">"):
        text = "\\" + text.lstrip()
    elif re.match(r"^\s*-\s", text) or re.match(r"^\s*\*\s", text):
        text = "\\" + text.lstrip()
    elif re.match(r"^\s*\d+\.\s", text):
        # Escape the dot so it becomes a literal number-dot.
        text = re.sub(r"^(\s*\d+)\.", r"\1\\.", text)
    return text


def _escape_table_cell(value: Any) -> str:
    """Escape a value for inclusion in a Markdown table cell.

    GFM tables do not allow literal pipe characters in cell content;
    pipes must be escaped with a backslash. Newlines are not allowed
    at all; the reporter converts them to ``<br>`` tags, which every
    GFM renderer interprets as a line break inside the cell.
    """
    if value is None:
        return _NOT_AVAILABLE
    if isinstance(value, (list, tuple, set, frozenset)):
        if not value:
            return _NOT_AVAILABLE
        return ", ".join(_escape_table_cell(v) for v in value)
    text = str(value)
    # Normalise line endings before processing.
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    # Escape pipes first (before we introduce <br>).
    text = text.replace("|", "\\|")
    # Convert newlines to <br>.
    text = text.replace("\n", "<br>")
    # Escape backslash-newline sequences that could be left over.
    # (Not needed in practice, but harmless.)
    return text


def _inline_code(value: Any) -> str:
    """Render ``value`` as inline code.

    The number of surrounding backticks is chosen so that the value's
    own backticks cannot terminate the span early. When the value
    starts or ends with a backtick, GFM requires a space between the
    delimiters and the content; the function adds one.
    """
    if value is None:
        return _NOT_AVAILABLE
    text = str(value)
    if not text:
        return "``"
    longest = _max_backtick_run(text)
    ticks = "`" * max(1, longest + 1)
    if text.startswith("`") or text.endswith("`"):
        return f"{ticks} {text} {ticks}"
    return f"{ticks}{text}{ticks}"


def _code_block(
    value: Any,
    *,
    lang: str = "",
    fence_char: str = DEFAULT_FENCE_CHAR,
) -> str:
    """Render ``value`` as a fenced code block.

    The fence length is chosen to be at least three and always at
    least one longer than the longest run of the fence character in
    the value. This guarantees the block cannot be closed early by
    its own content.

    A trailing newline is appended to the value if it does not
    already end with one, so that the closing fence always begins on
    its own line.
    """
    if value is None:
        return ""
    text = str(value)
    # Normalise line endings.
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    longest = _max_backtick_run(text) if fence_char == "`" else _longest_run(text, fence_char)
    fence = fence_char * max(3, longest + 1)
    opening = f"{fence}{lang}" if lang else fence
    if not text.endswith("\n"):
        text = text + "\n"
    return f"{opening}\n{text}{fence}"


def _longest_run(text: str, char: str) -> int:
    """Return the length of the longest run of ``char`` in ``text``."""
    if not text or not char:
        return 0
    longest = 0
    current = 0
    for c in text:
        if c == char:
            current += 1
            if current > longest:
                longest = current
        else:
            current = 0
    return longest


def _heading_text(value: Any) -> str:
    """Sanitise a value for use as heading content.

    Headings cannot contain newlines; the function collapses them to
    spaces. Leading and trailing whitespace is stripped. Other
    characters are preserved.
    """
    if value is None:
        return ""
    text = str(value)
    text = text.replace("\r\n", " ").replace("\r", " ").replace("\n", " ")
    return text.strip()


def _escape_link_text(value: Any) -> str:
    """Escape a value for use as the text portion of a Markdown link."""
    if value is None:
        return ""
    text = str(value)
    # Bracket characters must be escaped inside link text.
    text = text.replace("[", "\\[").replace("]", "\\]")
    # Collapse newlines.
    text = text.replace("\r\n", " ").replace("\r", " ").replace("\n", " ")
    return text


def _escape_link_target(value: Any) -> str:
    """Escape a value for use as the target of a Markdown link.

    Targets in GFM may contain most characters if wrapped in angle
    brackets; for simplicity the reporter percent-encodes spaces and
    angle brackets, which are the two characters most likely to cause
    trouble in practice.
    """
    if value is None:
        return ""
    text = str(value)
    text = text.replace(" ", "%20")
    text = text.replace("<", "%3C").replace(">", "%3E")
    return text


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------


def _format_datetime(value: Optional[datetime]) -> str:
    """Format a datetime for inclusion in Markdown.

    The ISO-8601 form is used because it sorts naturally, renders
    identically in every Markdown engine, and is unambiguous about
    the timezone. Naive datetimes are assumed to be UTC.
    """
    if value is None:
        return _NOT_AVAILABLE
    if not isinstance(value, datetime):
        return _escape_table_cell(value)
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    try:
        return value.isoformat(timespec="seconds")
    except Exception:  # noqa: BLE001
        return str(value)


def _format_bytes(value: Optional[int]) -> str:
    """Format a byte count as a human-readable string.

    The output is of the form ``"1.23 MiB (1290240 bytes)"``, showing
    both the human-readable and the exact value. The latter is
    important for archival accuracy.
    """
    if value is None:
        return _NOT_AVAILABLE
    try:
        n = int(value)
    except (TypeError, ValueError):
        return _escape_table_cell(value)
    if n < 1024:
        return f"{n} B"
    size = float(n)
    units = ["KiB", "MiB", "GiB", "TiB", "PiB"]
    for unit in units:
        size /= 1024.0
        if size < 1024.0:
            return f"{size:.2f} {unit} ({n:,} bytes)"
    return f"{n:,} bytes"


def _format_seconds(value: Optional[float]) -> str:
    """Format a duration in seconds."""
    if value is None:
        return _NOT_AVAILABLE
    try:
        s = float(value)
    except (TypeError, ValueError):
        return _escape_table_cell(value)
    if s < 1.0:
        return f"{s * 1000:.0f} ms"
    if s < 60.0:
        return f"{s:.2f} s"
    minutes, seconds = divmod(s, 60.0)
    if minutes < 60.0:
        return f"{int(minutes)}m {seconds:.0f}s"
    hours, minutes = divmod(minutes, 60.0)
    return f"{int(hours)}h {int(minutes)}m {seconds:.0f}s"


def _format_percent(value: Optional[float]) -> str:
    """Format a percentage value."""
    if value is None:
        return _NOT_AVAILABLE
    try:
        return f"{float(value):.2f} %"
    except (TypeError, ValueError):
        return _escape_table_cell(value)


def _severity_level_name(value: Any) -> str:
    """Normalise an arbitrary severity value to one of the canonical names."""
    if value is None:
        return "unknown"
    try:
        parsed = SeverityLevel.parse(value)
        name = getattr(parsed, "value", None)
        if isinstance(name, str):
            return name
    except Exception:  # noqa: BLE001
        pass
    text = str(value).strip().lower()
    if text in ("critical", "high", "medium", "low", "informational"):
        return text
    if text in ("info", "note", "informational"):
        return "informational"
    if text in ("severe",):
        return "high"
    if text in ("moderate", "med"):
        return "medium"
    return "unknown"


def _severity_badge(level_name: str) -> str:
    """Return a textual badge for a severity level.

    The badge uses uppercase text inside a bold marker rather than an
    emoji, so that it renders consistently across terminals, editors,
    and Markdown renderers.
    """
    display = {
        "critical": "CRITICAL",
        "high": "HIGH",
        "medium": "MEDIUM",
        "low": "LOW",
        "informational": "INFORMATIONAL",
        "unknown": "UNCLASSIFIED",
    }.get(level_name, "UNCLASSIFIED")
    return f"**\\[{display}\\]**"


def _truncate(text: str, limit: Optional[int]) -> Tuple[str, bool]:
    """Truncate ``text`` to ``limit`` characters; return (text, truncated)."""
    if limit is None or limit < 0 or len(text) <= limit:
        return text, False
    return text[:limit], True


def _slugify_anchor(text: str) -> str:
    """Return a URL-safe anchor for a Markdown heading.

    The rules are the ones GitHub uses: lowercase, replace spaces and
    non-alphanumeric characters with hyphens, collapse runs of
    hyphens, and trim leading and trailing hyphens. An empty result
    becomes ``"section"``.
    """
    slug = re.sub(r"[^a-zA-Z0-9\-]+", "-", text.lower())
    slug = re.sub(r"-+", "-", slug).strip("-")
    return slug or "section"


# ---------------------------------------------------------------------------
# MarkdownReporter
# ---------------------------------------------------------------------------


class MarkdownReporter:
    """Renders a :class:`ReportBundle` into Markdown.

    Parameters
    ----------
    options:
        Optional :class:`MarkdownOptions`. Defaults are used when
        omitted.

    Notes
    -----
    A reporter instance is stateless with respect to the bundle.
    Rendering the same bundle twice with the same options produces
    byte-identical output. Options are immutable, so a reporter may
    be shared safely across threads.
    """

    def __init__(self, options: Optional[MarkdownOptions] = None) -> None:
        self._options = options or MarkdownOptions()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @property
    def options(self) -> MarkdownOptions:
        return self._options

    def render(self, bundle: ReportBundle) -> str:
        """Render ``bundle`` to Markdown and return the resulting text.

        Raises
        ------
        MarkdownValidationError
            If the bundle fails pre-render validation.
        MarkdownSerializationError
            If a value in the bundle cannot be rendered.
        """
        if bundle is None:
            raise MarkdownValidationError("bundle must not be None")
        self._validate_bundle(bundle)

        sections: List[str] = []
        sections.append(self._render_title(bundle))
        if self._options.include_toc:
            toc = self._render_toc(bundle)
            if toc:
                sections.append(toc)
        if self._options.include_summary:
            sections.append(self._render_summary(bundle))
        if bundle.campaign is not None:
            sections.append(self._render_campaign(bundle.campaign))
        if bundle.corpus is not None:
            sections.append(self._render_corpus(bundle.corpus))
        if bundle.findings:
            sections.append(self._render_findings(bundle.findings))
        if bundle.supplemental_sections:
            sections.append(self._render_supplemental(bundle.supplemental_sections))
        if self._options.include_metadata_json:
            meta = self._render_metadata_json(bundle)
            if meta:
                sections.append(meta)
        sections.append(self._render_footer(bundle))

        text = "\n\n".join(s for s in sections if s)
        # Normalise any accidental multi-blank-line sequences.
        text = re.sub(r"\n{3,}", "\n\n", text)
        if self._options.trailing_newline and not text.endswith("\n"):
            text += "\n"
        return text

    def write(
        self,
        bundle: ReportBundle,
        path: Union[str, os.PathLike[str]],
    ) -> Path:
        """Render ``bundle`` and write it to ``path`` atomically.

        The file is written through a temporary sibling file, so that
        a partially-written report never appears on disk. Parent
        directories are created if necessary.

        Returns the absolute path of the written file.
        """
        target = Path(path).expanduser().resolve()
        target.parent.mkdir(parents=True, exist_ok=True)
        text = self.render(bundle)
        data = text.encode("utf-8")

        fd, tmp_name = tempfile.mkstemp(
            prefix=".kmcs-markdown-", dir=str(target.parent)
        )
        tmp_path = Path(tmp_name)
        try:
            with os.fdopen(fd, "wb") as fh:
                fh.write(data)
                fh.flush()
                try:
                    os.fsync(fh.fileno())
                except OSError:
                    pass
            os.replace(tmp_path, target)
        except Exception:
            try:
                tmp_path.unlink()
            except OSError:
                pass
            raise
        return target

    def write_stream(self, bundle: ReportBundle, stream: TextIO) -> None:
        """Write the rendered Markdown to an open text stream.

        The stream is not closed by this method.
        """
        stream.write(self.render(bundle))

    # ------------------------------------------------------------------
    # Bundle validation
    # ------------------------------------------------------------------

    def _validate_bundle(self, bundle: ReportBundle) -> None:
        """Reject bundles that would produce a malformed document."""
        metadata = getattr(bundle, "metadata", None)
        if metadata is None:
            raise MarkdownValidationError("bundle has no metadata")
        title = getattr(metadata, "title", None)
        if not isinstance(title, str) or not title.strip():
            raise MarkdownValidationError("bundle metadata has no title")

        seen: Dict[str, int] = {}
        findings = getattr(bundle, "findings", None) or ()
        for idx, finding in enumerate(findings):
            fid = getattr(finding, "finding_id", None)
            if not isinstance(fid, str) or not fid:
                raise MarkdownValidationError(
                    f"finding at index {idx} has no identifier"
                )
            if fid in seen:
                raise MarkdownValidationError(
                    f"duplicate finding identifier {fid!r} "
                    f"(indices {seen[fid]} and {idx})"
                )
            seen[fid] = idx

    # ------------------------------------------------------------------
    # Title section
    # ------------------------------------------------------------------

    def _render_title(self, bundle: ReportBundle) -> str:
        md = bundle.metadata
        parts: List[str] = []
        parts.append(f"# {_heading_text(md.title)}")
        if md.subtitle:
            parts.append(f"*{_escape_text(md.subtitle)}*")

        rows: List[Tuple[str, str]] = []
        rows.append(("Generated at", _format_datetime(md.generated_at)))
        if md.generator:
            rows.append(("Generator", _escape_table_cell(md.generator)))
        if md.campaign_id:
            rows.append(("Campaign ID", _inline_code(md.campaign_id)))
        if md.campaign_name:
            rows.append(("Campaign", _escape_table_cell(md.campaign_name)))
        if md.fuzzer:
            rows.append(("Fuzzer", _inline_code(md.fuzzer)))
        if md.sanitizer:
            rows.append(("Sanitizer", _inline_code(md.sanitizer)))
        if md.target_description:
            rows.append(("Target", _inline_code(md.target_description)))

        if rows:
            parts.append(self._render_kv_table(rows))

        if md.notes:
            note_lines = [f"- {_escape_text(n)}" for n in md.notes]
            parts.append("\n".join(note_lines))

        return "\n\n".join(parts)

    # ------------------------------------------------------------------
    # Table of contents
    # ------------------------------------------------------------------

    def _render_toc(self, bundle: ReportBundle) -> str:
        entries: List[Tuple[str, str]] = []
        if self._options.include_summary:
            entries.append(("summary", "Summary"))
        if bundle.campaign is not None:
            entries.append(("campaign", "Campaign"))
        if bundle.corpus is not None:
            entries.append(("corpus", "Corpus"))
        if bundle.findings:
            entries.append(("findings", "Findings"))
            entries.append(("findings-overview", "Findings overview"))
        for title, _ in bundle.supplemental_sections:
            entries.append((_slugify_anchor(title), title))
        if self._options.include_metadata_json:
            entries.append(("report-data", "Report data"))

        if len(entries) < 2:
            return ""

        lines = ["## Table of contents", ""]
        for anchor, label in entries:
            lines.append(f"- [{_escape_link_text(label)}](#{anchor})")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------

    def _render_summary(self, bundle: ReportBundle) -> str:
        findings = bundle.findings or ()
        total = len(findings)

        severity_counts = {name: 0 for name in _SEVERITY_LEVELS}
        for finding in findings:
            level = _severity_level_name(getattr(finding, "severity", None))
            severity_counts[level] = severity_counts.get(level, 0) + 1

        reproduced = self._count_reproduced(findings)

        rows: List[Tuple[str, str]] = []
        rows.append(("Total findings", str(total)))
        for level_name in ("critical", "high", "medium", "low", "informational"):
            count = severity_counts.get(level_name, 0)
            if count or level_name in ("critical", "high"):
                rows.append((level_name.capitalize(), str(count)))
        unknown = severity_counts.get("unknown", 0)
        if unknown:
            rows.append(("Unclassified", str(unknown)))
        if total:
            rows.append(("Reproduced", f"{reproduced} / {total}"))

        body = [self._render_kv_table(rows)]

        if total == 0:
            body.insert(
                0,
                "> This report contains no findings. The bundle was "
                "rendered successfully; there were no finding records "
                "to include.",
            )

        # Classification breakdown when more than one classification
        # is present, since otherwise it duplicates the severity table.
        classification_counts = self._count_classifications(findings)
        if len(classification_counts) > 1:
            rows_c: List[Tuple[str, str]] = []
            for name, count in sorted(
                classification_counts.items(),
                key=lambda kv: (-kv[1], kv[0]),
            ):
                rows_c.append((name, str(count)))
            body.append("### By classification")
            body.append(self._render_kv_table(rows_c))

        return "\n\n".join(["## Summary"] + body)

    # ------------------------------------------------------------------
    # Campaign
    # ------------------------------------------------------------------

    def _render_campaign(self, campaign: ReportCampaignSummary) -> str:
        rows: List[Tuple[str, str]] = []

        def add(label: str, value: Any) -> None:
            rows.append((label, _escape_table_cell(value)))

        if campaign.name is not None:
            add("Name", campaign.name)
        if campaign.campaign_id is not None:
            rows.append(("Campaign ID", _inline_code(campaign.campaign_id)))
        if campaign.state is not None:
            rows.append(("State", _inline_code(campaign.state)))
        if campaign.fuzzer is not None:
            rows.append(("Fuzzer", _inline_code(campaign.fuzzer)))
        if campaign.sanitizer is not None:
            rows.append(("Sanitizer", _inline_code(campaign.sanitizer)))
        if campaign.target_command is not None:
            rows.append(("Target", _inline_code(campaign.target_command)))
        if campaign.workers is not None:
            add("Workers", campaign.workers)
        if campaign.started_at is not None:
            add("Started", _format_datetime(campaign.started_at))
        if campaign.finished_at is not None:
            add("Finished", _format_datetime(campaign.finished_at))
        if campaign.runtime_seconds is not None:
            add("Runtime", _format_seconds(campaign.runtime_seconds))
        if campaign.total_executions is not None:
            add("Executions", f"{campaign.total_executions:,}")
        if campaign.total_crashes is not None:
            add("Crashes", campaign.total_crashes)
        if campaign.total_hangs is not None:
            add("Hangs", campaign.total_hangs)
        if campaign.coverage_percent is not None:
            add("Coverage", _format_percent(campaign.coverage_percent))
        if campaign.corpus_size is not None:
            add("Corpus size", campaign.corpus_size)
        if campaign.tags:
            add("Tags", ", ".join(sorted(campaign.tags)))
        if campaign.error_message:
            add("Error", campaign.error_message)

        if not rows:
            return ""
        return "## Campaign\n\n" + self._render_kv_table(rows)

    # ------------------------------------------------------------------
    # Corpus
    # ------------------------------------------------------------------

    def _render_corpus(self, corpus: ReportCorpusSummary) -> str:
        rows: List[Tuple[str, str]] = []

        def add(label: str, value: Any) -> None:
            rows.append((label, _escape_table_cell(value)))

        if corpus.root is not None:
            rows.append(("Root", _inline_code(corpus.root)))
        if corpus.total_entries is not None:
            add("Entries", f"{corpus.total_entries:,}")
        if corpus.unique_digests is not None:
            add("Unique digests", f"{corpus.unique_digests:,}")
        if corpus.total_bytes is not None:
            add("Total size", _format_bytes(corpus.total_bytes))
        if corpus.smallest_size is not None:
            add("Smallest input", _format_bytes(corpus.smallest_size))
        if corpus.largest_size is not None:
            add("Largest input", _format_bytes(corpus.largest_size))
        if corpus.mean_size is not None:
            add("Mean size", f"{corpus.mean_size:,.1f} bytes")
        if corpus.median_size is not None:
            add("Median size", f"{corpus.median_size:,.1f} bytes")

        if not rows:
            return ""
        return "## Corpus\n\n" + self._render_kv_table(rows)

    # ------------------------------------------------------------------
    # Findings
    # ------------------------------------------------------------------

    def _render_findings(
        self, findings: Sequence[ReportFinding]
    ) -> str:
        sorted_findings = self._sort_findings(findings)

        parts: List[str] = [f"## Findings ({len(sorted_findings)})"]
        parts.append(self._render_findings_overview(sorted_findings))
        for idx, finding in enumerate(sorted_findings):
            parts.append(self._render_finding(finding, idx))

        return "\n\n".join(parts)

    @staticmethod
    def _sort_findings(
        findings: Sequence[ReportFinding],
    ) -> List[ReportFinding]:
        """Return findings sorted by severity then by discovery time.

        Severity ordering is the canonical order defined by
        :data:`_SEVERITY_ORDER`. Within a severity level, findings
        are ordered by discovery time (newest first). Ties are broken
        by finding identifier to guarantee determinism.
        """
        def key(f: ReportFinding) -> Tuple[int, float, str]:
            level = _severity_level_name(getattr(f, "severity", None))
            sev_rank = _SEVERITY_ORDER.get(level, 99)
            discovered = getattr(f, "discovered_at", None)
            if isinstance(discovered, datetime):
                ts = -discovered.timestamp()
            else:
                ts = 0.0
            fid = str(getattr(f, "finding_id", ""))
            return (sev_rank, ts, fid)

        return sorted(findings, key=key)

    def _render_findings_overview(
        self, findings: Sequence[ReportFinding]
    ) -> str:
        """Render the summary table that precedes the detailed findings."""
        if not findings:
            return ""
        header = (
            "| # | Severity | Finding | Classification | Reproduced |\n"
            "| --- | --- | --- | --- | --- |"
        )
        lines = [header]
        for idx, finding in enumerate(findings):
            level = _severity_level_name(getattr(finding, "severity", None))
            severity_display = {
                "critical": "**Critical**",
                "high": "**High**",
                "medium": "Medium",
                "low": "Low",
                "informational": "Informational",
                "unknown": "_unclassified_",
            }.get(level, "_unclassified_")

            title = getattr(finding, "title", "") or ""
            anchor = f"finding-{_slugify_anchor(str(getattr(finding, 'finding_id', idx)))}"
            title_link = f"[{_escape_link_text(title)}](#{anchor})"

            classification = (
                getattr(finding, "classification_label", None)
                or getattr(finding, "classification", None)
                or getattr(finding, "crash_kind", None)
            )
            classification_cell = (
                _escape_table_cell(classification)
                if classification is not None
                else _NOT_AVAILABLE
            )

            reproduced = self._is_reproduced(finding)
            reproduced_cell = "yes" if reproduced else "no" if reproduced is False else _NOT_AVAILABLE

            lines.append(
                f"| {idx + 1} | {severity_display} | {title_link} | "
                f"{classification_cell} | {reproduced_cell} |"
            )
        return "\n".join(lines)

    def _render_finding(self, finding: ReportFinding, index: int) -> str:
        """Render a single finding as a top-level subsection."""
        fid = str(getattr(finding, "finding_id", f"finding-{index}"))
        anchor_id = f"finding-{_slugify_anchor(fid)}"

        level = _severity_level_name(getattr(finding, "severity", None))
        badge = _severity_badge(level)
        title = _heading_text(getattr(finding, "title", "") or f"Finding {index + 1}")

        parts: List[str] = []
        # Explicit anchor so that the overview table's links resolve
        # regardless of how the renderer slugifies the heading.
        parts.append(f'<a id="{anchor_id}"></a>')
        parts.append(f"### {badge} {title}")
        parts.append(f"**Finding ID:** {_inline_code(fid)}")

        overview_rows = self._finding_overview_rows(finding)
        if overview_rows:
            parts.append(self._render_kv_table(overview_rows))

        process = self._render_finding_process(finding)
        if process:
            parts.append(process)

        source = self._render_finding_source(finding)
        if source:
            parts.append(source)

        stack = self._render_finding_stack(finding)
        if stack:
            parts.append(stack)

        repro = self._render_finding_reproduction(finding)
        if repro:
            parts.append(repro)

        evidence = self._render_finding_evidence(finding)
        if evidence:
            parts.append(evidence)

        notes = self._render_finding_notes(finding)
        if notes:
            parts.append(notes)

        metadata = self._render_finding_metadata(finding)
        if metadata:
            parts.append(metadata)

        return "\n\n".join(parts)

    def _finding_overview_rows(
        self, finding: ReportFinding
    ) -> List[Tuple[str, str]]:
        rows: List[Tuple[str, str]] = []

        def add(label: str, value: str) -> None:
            rows.append((label, value))

        severity_raw = getattr(finding, "severity", None)
        if severity_raw is not None:
            level = _severity_level_name(severity_raw)
            display = {
                "critical": "**Critical**",
                "high": "**High**",
                "medium": "Medium",
                "low": "Low",
                "informational": "Informational",
                "unknown": "_unclassified_",
            }.get(level, _escape_table_cell(severity_raw))
            add("Severity", display)

        crash_kind = getattr(finding, "crash_kind", None)
        if crash_kind is not None:
            add("Crash kind", _inline_code(crash_kind))

        classification_label = getattr(finding, "classification_label", None)
        classification = getattr(finding, "classification", None)
        if classification_label is not None:
            add("Classification", _escape_table_cell(classification_label))
        elif classification is not None:
            add("Classification", _inline_code(classification))

        sanitizer = getattr(finding, "sanitizer", None)
        if sanitizer is not None:
            add("Sanitizer", _inline_code(sanitizer))

        fingerprint = getattr(finding, "fingerprint", None)
        if fingerprint is not None:
            add("Fingerprint", _inline_code(fingerprint))

        digest = getattr(finding, "input_digest", None)
        if digest is not None:
            add("Input digest", _inline_code(digest))

        size = getattr(finding, "input_size", None)
        if size is not None:
            add("Input size", _format_bytes(size))

        path = getattr(finding, "input_path", None)
        if path is not None:
            add("Input path", _inline_code(path))

        discovered = getattr(finding, "discovered_at", None)
        if discovered is not None:
            add("Discovered", _format_datetime(discovered))

        discovered_by = getattr(finding, "discovered_by", None)
        if discovered_by is not None:
            add("Discovered by", _escape_table_cell(discovered_by))

        tags = getattr(finding, "tags", None) or frozenset()
        if tags:
            add("Tags", _escape_table_cell(", ".join(sorted(tags))))

        return rows

    def _render_finding_process(self, finding: ReportFinding) -> str:
        rows: List[Tuple[str, str]] = []

        exit_code = getattr(finding, "exit_code", None)
        if exit_code is not None:
            rows.append(("Exit code", _inline_code(exit_code)))

        signal_number = getattr(finding, "signal_number", None)
        signal_name = getattr(finding, "signal_name", None)
        if signal_number is not None or signal_name is not None:
            if signal_name and signal_number is not None:
                cell = f"{_inline_code(signal_name)} ({_escape_table_cell(signal_number)})"
            elif signal_name:
                cell = _inline_code(signal_name)
            else:
                cell = _inline_code(signal_number)
            rows.append(("Signal", cell))

        timed_out = getattr(finding, "timed_out", None)
        if timed_out is not None:
            rows.append(("Timed out", "yes" if timed_out else "no"))

        fault = getattr(finding, "fault_address", None)
        if fault is not None:
            rows.append(("Fault address", _inline_code(fault)))

        access = getattr(finding, "access_type", None)
        if access is not None:
            rows.append(("Access type", _inline_code(access)))

        if not rows:
            return ""
        return "#### Process\n\n" + self._render_kv_table(rows)

    def _render_finding_source(self, finding: ReportFinding) -> str:
        location = getattr(finding, "source_location", None)
        if not location or not isinstance(location, Mapping):
            return ""
        file_ = location.get("file")
        line = location.get("line")
        column = location.get("column")
        function = location.get("function")

        parts: List[str] = []
        if function:
            parts.append(_inline_code(function))
        if file_:
            location_text = str(file_)
            if line is not None:
                location_text += f":{line}"
                if column is not None:
                    location_text += f":{column}"
            parts.append(_inline_code(location_text))
        if not parts:
            return ""
        return "#### Source location\n\n" + " at ".join(parts)

    def _render_finding_stack(self, finding: ReportFinding) -> str:
        frames = getattr(finding, "stack_frames", None) or ()
        if not frames:
            return ""
        rows: List[str] = []
        for idx, frame in enumerate(frames):
            if not isinstance(frame, Mapping):
                rows.append((str(idx), _escape_table_cell(frame), "", ""))
                continue
            function = frame.get("function") or frame.get("func") or ""
            file_ = frame.get("file") or frame.get("filename") or ""
            line = frame.get("line") or frame.get("lineno") or ""
            offset = frame.get("offset") or frame.get("pc") or ""
            location_cell = str(file_)
            if line:
                location_cell += f":{line}"
            rows.append(
                (
                    str(idx),
                    _escape_table_cell(function),
                    _escape_table_cell(location_cell) if location_cell else _NOT_AVAILABLE,
                    _escape_table_cell(offset) if offset else _NOT_AVAILABLE,
                )
            )

        lines = [
            "#### Stack trace",
            "",
            "| # | Function | Location | Offset |",
            "| --- | --- | --- | --- |",
        ]
        for idx, function, location, offset in rows:
            lines.append(f"| {idx} | {function} | {location} | {offset} |")
        return "\n".join(lines)

    def _render_finding_reproduction(self, finding: ReportFinding) -> str:
        rows: List[Tuple[str, str]] = []

        repro_status = getattr(finding, "reproduction_status", None)
        if repro_status is not None:
            rows.append(("Reproduction", self._status_cell(repro_status)))

        attempts = getattr(finding, "reproduction_attempts", None)
        matched = getattr(finding, "reproduction_matched", None)
        if attempts is not None or matched is not None:
            if attempts is not None and matched is not None:
                rows.append(
                    ("Attempts", f"{matched} matched / {attempts} total")
                )
            elif attempts is not None:
                rows.append(("Attempts", str(attempts)))

        regression_status = getattr(finding, "regression_status", None)
        if regression_status is not None:
            rows.append(("Regression", self._status_cell(regression_status)))

        regression_runs = getattr(finding, "regression_runs", None)
        if regression_runs is not None:
            rows.append(("Regression runs", str(regression_runs)))

        if not rows:
            return ""
        return "#### Reproduction\n\n" + self._render_kv_table(rows)

    @staticmethod
    def _status_cell(value: Any) -> str:
        """Return a table cell for a status value with a strong prefix."""
        text = str(value).strip()
        if not text:
            return _NOT_AVAILABLE
        lowered = text.lower()
        if lowered in ("reproduced", "passed"):
            return f"**{_escape_table_cell(text)}**"
        if lowered in ("not_reproduced", "failed"):
            return f"**{_escape_table_cell(text)}**"
        return _escape_table_cell(text)

    def _render_finding_evidence(self, finding: ReportFinding) -> str:
        if not self._options.include_raw_output:
            return ""
        raw = getattr(finding, "raw_output", None)
        if raw is None or not isinstance(raw, str) or not raw:
            return ""

        text, truncated = _truncate(raw, self._options.max_output_chars)
        block = _code_block(
            text,
            lang="",
            fence_char=self._options.fence_char,
        )

        truncated_notice = ""
        if truncated:
            truncated_notice = (
                f"> Output truncated at {self._options.max_output_chars:,} "
                "characters by the reporter.\n\n"
            )

        body = f"{truncated_notice}{block}"

        if self._options.use_details_blocks:
            return (
                "#### Evidence\n\n"
                "<details>\n"
                "<summary>Raw crash output</summary>\n\n"
                f"{body}\n\n"
                "</details>"
            )
        return "#### Evidence\n\n" + body

    def _render_finding_notes(self, finding: ReportFinding) -> str:
        notes = getattr(finding, "notes", None) or ()
        if not notes:
            return ""
        lines = ["#### Notes", ""]
        for note in notes:
            lines.append(f"- {_escape_text(note)}")
        return "\n".join(lines)

    def _render_finding_metadata(self, finding: ReportFinding) -> str:
        metadata = getattr(finding, "metadata", None)
        if not metadata:
            return ""
        try:
            text = json.dumps(
                dict(metadata),
                indent=2,
                sort_keys=True,
                default=str,
            )
        except Exception as exc:  # noqa: BLE001
            raise MarkdownSerializationError(
                f"failed to serialise finding metadata: {exc}"
            ) from exc

        block = _code_block(
            text, lang="json", fence_char=self._options.fence_char
        )

        if self._options.use_details_blocks:
            return (
                "#### Metadata\n\n"
                "<details>\n"
                "<summary>Additional metadata</summary>\n\n"
                f"{block}\n\n"
                "</details>"
            )
        return "#### Metadata\n\n" + block

    # ------------------------------------------------------------------
    # Supplemental sections
    # ------------------------------------------------------------------

    def _render_supplemental(
        self,
        sections: Sequence[Tuple[str, str]],
    ) -> str:
        if not sections:
            return ""
        parts: List[str] = []
        for title, body in sections:
            anchor = _slugify_anchor(title)
            parts.append(f'<a id="{anchor}"></a>')
            parts.append(f"## {_heading_text(title)}")
            if body:
                parts.append(body)
        return "\n\n".join(parts)

    # ------------------------------------------------------------------
    # Report data section
    # ------------------------------------------------------------------

    def _render_metadata_json(self, bundle: ReportBundle) -> str:
        try:
            if hasattr(bundle, "to_dict"):
                payload = bundle.to_dict()
            else:
                payload = {
                    "metadata": getattr(bundle.metadata, "to_dict", lambda: {})()  # type: ignore[union-attr]
                    if bundle.metadata is not None else None,
                    "findings": [
                        f.to_dict() for f in (bundle.findings or ())
                        if hasattr(f, "to_dict")
                    ],
                }
            text = json.dumps(payload, indent=2, sort_keys=True, default=str)
        except Exception as exc:  # noqa: BLE001
            return (
                "## Report data\n\n"
                f"> Failed to serialise report data: {_escape_text(str(exc))}"
            )

        block = _code_block(
            text, lang="json", fence_char=self._options.fence_char
        )

        if self._options.use_details_blocks:
            return (
                '<a id="report-data"></a>\n'
                "## Report data\n\n"
                "<details>\n"
                "<summary>Underlying bundle as JSON</summary>\n\n"
                f"{block}\n\n"
                "</details>"
            )
        return '<a id="report-data"></a>\n## Report data\n\n' + block

    # ------------------------------------------------------------------
    # Footer
    # ------------------------------------------------------------------

    def _render_footer(self, bundle: ReportBundle) -> str:
        generator = getattr(bundle.metadata, "generator", None) or (
            f"{GENERATOR_NAME} {GENERATOR_VERSION}"
        )
        generated_at = getattr(bundle.metadata, "generated_at", None)
        when = _format_datetime(generated_at) if isinstance(generated_at, datetime) else _escape_text(generated_at)
        return f"*Generated by {_escape_text(generator)} at {when}*"

    # ------------------------------------------------------------------
    # Generic rendering helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _render_kv_table(rows: Sequence[Tuple[str, str]]) -> str:
        """Render a two-column key/value table.

        The key column is bolded by the caller; this helper only
        emits the table skeleton and escapes cells. Rows whose value
        is already preformatted (contains Markdown markup) should be
        passed through unchanged; the caller is responsible for
        escaping.
        """
        if not rows:
            return ""
        lines = ["| Field | Value |", "| --- | --- |"]
        for key, value in rows:
            if value is None or value == "":
                value = _NOT_AVAILABLE
            lines.append(f"| {_escape_table_cell(key)} | {value} |")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Counting helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _count_reproduced(findings: Sequence[ReportFinding]) -> int:
        total = 0
        for finding in findings:
            if MarkdownReporter._is_reproduced(finding) is True:
                total += 1
        return total

    @staticmethod
    def _is_reproduced(finding: ReportFinding) -> Optional[bool]:
        """Return True/False/None depending on the reproduction status."""
        status = getattr(finding, "reproduction_status", None)
        if status is None:
            return None
        text = str(status).strip().lower()
        if text == "reproduced":
            return True
        if text in ("not_reproduced", "failed"):
            return False
        return None

    @staticmethod
    def _count_classifications(
        findings: Sequence[ReportFinding],
    ) -> Dict[str, int]:
        counts: Dict[str, int] = {}
        for finding in findings:
            key = (
                getattr(finding, "classification_label", None)
                or getattr(finding, "classification", None)
                or getattr(finding, "crash_kind", None)
                or "unclassified"
            )
            key_str = str(key)
            counts[key_str] = counts.get(key_str, 0) + 1
        return counts

    # ------------------------------------------------------------------
    # Representation
    # ------------------------------------------------------------------

    def __repr__(self) -> str:
        opts = self._options
        return (
            f"MarkdownReporter(include_toc={opts.include_toc}, "
            f"include_summary={opts.include_summary}, "
            f"include_metadata_json={opts.include_metadata_json})"
        )


# ---------------------------------------------------------------------------
# Convenience functions
# ---------------------------------------------------------------------------


def render_markdown(
    bundle: ReportBundle,
    *,
    options: Optional[MarkdownOptions] = None,
) -> str:
    """Render ``bundle`` to Markdown using the given options.

    This is a one-shot wrapper around :class:`MarkdownReporter` for
    callers who do not need to reuse a reporter instance.
    """
    reporter = MarkdownReporter(options)
    return reporter.render(bundle)


def dump_markdown_string(
    bundle: ReportBundle,
    *,
    options: Optional[MarkdownOptions] = None,
) -> str:
    """Alias for :func:`render_markdown`.

    Provided for symmetry with :mod:`kmcs.reporting.json_report`,
    which names its string-producing helper ``dump_json_string``.
    """
    return render_markdown(bundle, options=options)


def dump_markdown(
    bundle: ReportBundle,
    path: Union[str, os.PathLike[str]],
    *,
    options: Optional[MarkdownOptions] = None,
) -> Path:
    """Render ``bundle`` and write it to ``path`` atomically.

    Returns the absolute path of the written file.
    """
    reporter = MarkdownReporter(options)
    return reporter.write(bundle, path)


def write_markdown(
    bundle: ReportBundle,
    path: Union[str, os.PathLike[str]],
    *,
    options: Optional[MarkdownOptions] = None,
) -> Path:
    """Alias for :func:`dump_markdown`.

    Provided because callers who work with the HTML reporter
    naturally reach for ``write_html`` and expect a symmetric name.
    """
    return dump_markdown(bundle, path, options=options)


# ---------------------------------------------------------------------------
# Format description
# ---------------------------------------------------------------------------


def describe_format() -> Dict[str, Any]:
    """Return a machine-readable description of the emitted format.

    The description is intended for tooling that consumes Markdown
    reports and needs to know which structural features may appear.
    It is not a formal schema; Markdown has no schema language.
    """
    return {
        "format": "markdown",
        "flavor": "gfm",
        "features_used": [
            "headings",
            "tables",
            "fenced_code_blocks",
            "bullet_lists",
            "blockquotes",
            "html_details_summary",
            "html_anchors",
            "inline_code",
            "bold_italic",
        ],
        "sections": [
            {
                "anchor": "summary",
                "heading": "Summary",
                "optional": True,
                "description": "Aggregate counts derived from the findings list.",
            },
            {
                "anchor": "campaign",
                "heading": "Campaign",
                "optional": True,
                "description": "Campaign configuration and final statistics.",
            },
            {
                "anchor": "corpus",
                "heading": "Corpus",
                "optional": True,
                "description": "Corpus statistics.",
            },
            {
                "anchor": "findings",
                "heading": "Findings",
                "optional": True,
                "description": (
                    "One subsection per finding. Anchors are of the "
                    "form ``finding-<slug>``."
                ),
            },
            {
                "anchor": "report-data",
                "heading": "Report data",
                "optional": True,
                "description": (
                    "The underlying bundle serialised as JSON inside "
                    "a collapsible block."
                ),
            },
        ],
        "escaping": {
            "table_cells": "Pipe characters are escaped; newlines become <br>.",
            "inline_code": "Backtick length is chosen to avoid collisions.",
            "code_blocks": "Fence length is chosen to avoid collisions.",
            "headings": "Newlines are collapsed; leading markup is escaped.",
        },
        "ordering": {
            "findings": (
                "Severity descending; within a severity, discovery time "
                "descending; ties broken by finding identifier."
            ),
            "tables": "Rows appear in insertion order; keys are not sorted.",
        },
    }


# ---------------------------------------------------------------------------
# Module metadata
# ---------------------------------------------------------------------------

__version__ = "1.0.0"
