"""
KMCS core foundation (Phase 1)
==============================

The ``kmcs.core`` package provides the five pillars every other subsystem is
built on:

``config``
    Pydantic-validated, layered configuration (defaults → file → environment →
    CLI overrides), with profiles, secret-safe serialisation and atomic writes.

``events``
    A thread-safe, lock-free-per-subscriber in-process event bus with topics,
    wildcards, filtering, throttling, replay, async dispatch and metrics — the
    backbone of live campaign telemetry for the future GUI/CLI.

``jobs``
    A finite-state job engine with dependency resolution, topological planning,
    retries with exponential backoff, cancellation tokens, leases, resource
    accounting and a pluggable executor interface.

``models``
    The domain model vocabulary: enums, value objects and immutable dataclasses
    describing targets, corpora, campaigns, crashes, findings, reports and the
    toolchain inventory.

``exceptions``
    The structured error taxonomy (codes, severities, context, redaction,
    registry, remediation guidance).

Nothing in this package talks to the network and nothing requires an API key or
credential of any kind.  KMCS is fully offline by design.

Security note
-------------
This package enforces the defensive-use charter declared in :mod:`kmcs`
(:data:`kmcs.PROHIBITED_CAPABILITIES`).  Requests for exploit generation,
shellcode, weaponisation, persistence, credential theft, unauthorised scanning,
stealth or security-control bypass raise
:class:`kmcs.core.exceptions.PolicyViolationError`.
"""

from __future__ import annotations

from typing import Dict, List

from kmcs.core.exceptions import (
    AuthorizationError,
    ConfigurationError,
    ConsentRequiredError,
    CorpusError,
    CrashError,
    DatabaseError,
    EnvironmentErrorDetail,
    ErrorCode,
    ErrorContext,
    ErrorSeverity,
    EventError,
    ExceptionRegistry,
    FuzzingError,
    JobError,
    KMCSAssertionError,
    KMCSBaseError,
    KMCSTypeError,
    KMCSUsageError,
    KMCSValueError,
    KMCSOSError,
    KMCSRuntimeError,
    PolicyViolationError,
    ProhibitedCapabilityError,
    ReportError,
    ResourceError,
    TargetError,
    ToolNotFoundError,
    exception_registry,
    format_exception,
    redact,
)
from kmcs.core.config import (
    ASAN_OPTIONS_DEFAULTS,
    CampaignConfig,
    ConfigManager,
    ConfigResult,
    ConfigSnapshot,
    CorpusConfig,
    CoverageConfig,
    DEFAULT_CONFIG,
    EngineKind,
    EnvironmentProfile,
    FuzzerConfig,
    InstrumentationConfig,
    KmcsConfig,
    LSanOptions,
    MinimizationConfig,
    NotificationConfig,
    PathsConfig,
    PerformanceConfig,
    ReproductionConfig,
    ReportingConfig,
    ResourceLimits,
    RuntimeStatus,
    SanitizerFlag,
    SanitizersConfig,
    TelemetryConfig,
    UBSanOptions,
    ValidationIssue,
    VerificationReport,
    WorkerConfig,
    load_config,
    resolve_environment,
)
from kmcs.core.events import (
    AsyncEventBus,
    BufferedSubscriber,
    EventBus,
    EventFilter,
    EventSink,
    EventType,
    FNV1a,
    InMemorySink,
    JsonLineFileSink,
    Record,
    SubscriberHandle,
    Topic,
    TopicTrie,
    content_hash,
    current_bus,
    emit,
    subscribe,
)
from kmcs.core.jobs import (
    BackoffPolicy,
    CancellationError,
    CancellationRegistry,
    CancellationScope,
    Cancellation,
    DependencyGraph,
    ExecutionRecord,
    Executor,
    FunctionExecutor,
    JobBuilder,
    JobDefinition,
    JobKind,
    JobPlan,
    JobPriority,
    JobResult,
    JobState,
    JobView,
    Lease,
    NoExecutorAvailable,
    Progress,
    RetryPolicy,
    ResourceManager,
    StateTransition,
    WorkItem,
)
from kmcs.core.models import (
    Architecture,
    Authorisation,
    BuildRecipe,
    CompilerFamily,
    Crash,
    CrashClass,
    CrashState,
    Corpus,
    CorpusEntry,
    DedupDecision,
    EngineCapabilities,
    EngineKind as ModelEngineKind,
    Evidence,
    Finding,
    FindingState,
    InputClass,
    InstrumentationKind,
    Language,
    LinkageKind,
    MemoryAccessType,
    OperationMode,
    Priority,
    ProcessRole,
    ProductIdentity,
    Reproducer,
    ReproductionOutcome,
    ReproductionResult,
    ReportFormat,
    ReportRequest,
    RootCauseHint,
    RunMetrics,
    RunStatus,
    SanitizerKind,
    Severity,
    SignalInfo,
    SourceLayout,
    StackFrame,
    SymbolizerKind,
    Target,
    TargetKind,
    TaskSpec,
    ToolAvailability,
    ToolchainProbe,
    TriggerCondition,
    Vote,
    build_default_registry,
    compute_fingerprint,
    default_timestamp,
    derive_severity,
    dump_json,
    fingerprint_of,
    generate_prefixed_id,
    guess_language,
    input_class_for,
    is_prohibited_capability,
    load_json,
    make_authorisation,
    normalise_name,
    now_utc,
    parse_size,
    register_model,
    safe_filename,
    sha256_bytes,
    sha256_file,
    stable_digest,
    to_snake,
    to_title,
    utc_string,
)

__all__: List[str] = [
    # exceptions
    "ErrorCode",
    "ErrorSeverity",
    "ErrorContext",
    "ExceptionRegistry",
    "exception_registry",
    "KMCSBaseError",
    "KMCSRuntimeError",
    "KMCSValueError",
    "KMCSTypeError",
    "KMCSOSError",
    "KMCSUsageError",
    "KMCSAssertionError",
    "ConfigurationError",
    "AuthorizationError",
    "ConsentRequiredError",
    "PolicyViolationError",
    "ProhibitedCapabilityError",
    "EnvironmentErrorDetail",
    "ToolNotFoundError",
    "TargetError",
    "FuzzingError",
    "CorpusError",
    "CrashError",
    "JobError",
    "DatabaseError",
    "EventError",
    "ReportError",
    "ResourceError",
    "redact",
    "format_exception",
    # config
    "KmcsConfig",
    "ConfigManager",
    "ConfigResult",
    "ConfigSnapshot",
    "PathsConfig",
    "PerformanceConfig",
    "ResourceLimits",
    "EnvironmentProfile",
    "InstrumentationConfig",
    "CorpusConfig",
    "FuzzerConfig",
    "CampaignConfig",
    "WorkerConfig",
    "SanitizersConfig",
    "ASAN_OPTIONS_DEFAULTS",
    "UBSanOptions",
    "LSanOptions",
    "CoverageConfig",
    "ReproductionConfig",
    "MinimizationConfig",
    "ReportingConfig",
    "TelemetryConfig",
    "NotificationConfig",
    "ValidationIssue",
    "VerificationReport",
    "EngineKind",
    "SanitizerFlag",
    "RuntimeStatus",
    "load_config",
    "resolve_environment",
    # events
    "EventType",
    "Topic",
    "TopicTrie",
    "Record",
    "EventBus",
    "AsyncEventBus",
    "EventFilter",
    "EventSink",
    "InMemorySink",
    "JsonLineFileSink",
    "BufferedSubscriber",
    "SubscriberHandle",
    "FNV1a",
    "content_hash",
    "emit",
    "subscribe",
    "current_bus",
    # jobs
    "JobState",
    "JobKind",
    "JobPriority",
    "JobDefinition",
    "JobBuilder",
    "WorkItem",
    "ExecutionRecord",
    "JobResult",
    "JobView",
    "JobPlan",
    "DependencyGraph",
    "StateTransition",
    "Lease",
    "Progress",
    "RetryPolicy",
    "BackoffPolicy",
    "Cancellation",
    "CancellationScope",
    "CancellationRegistry",
    "CancellationError",
    "Executor",
    "FunctionExecutor",
    "NoExecutorAvailable",
    "ResourceManager",
    # models
    "Architecture",
    "Authorisation",
    "BuildRecipe",
    "CompilerFamily",
    "Crash",
    "CrashClass",
    "CrashState",
    "Corpus",
    "CorpusEntry",
    "DedupDecision",
    "EngineCapabilities",
    "ModelEngineKind",
    "Evidence",
    "Finding",
    "FindingState",
    "InputClass",
    "InstrumentationKind",
    "Language",
    "LinkageKind",
    "MemoryAccessType",
    "OperationMode",
    "Priority",
    "ProcessRole",
    "ProductIdentity",
    "Reproducer",
    "ReproductionOutcome",
    "ReproductionResult",
    "ReportFormat",
    "ReportRequest",
    "RootCauseHint",
    "RunMetrics",
    "RunStatus",
    "SanitizerKind",
    "Severity",
    "SignalInfo",
    "SourceLayout",
    "StackFrame",
    "SymbolizerKind",
    "Target",
    "TargetKind",
    "TaskSpec",
    "ToolAvailability",
    "ToolchainProbe",
    "TriggerCondition",
    "Vote",
    "build_default_registry",
    "compute_fingerprint",
    "default_timestamp",
    "derive_severity",
    "dump_json",
    "fingerprint_of",
    "generate_prefixed_id",
    "guess_language",
    "input_class_for",
    "is_prohibited_capability",
    "load_json",
    "make_authorisation",
    "normalise_name",
    "now_utc",
    "parse_size",
    "register_model",
    "safe_filename",
    "sha256_bytes",
    "sha256_file",
    "stable_digest",
    "to_snake",
    "to_title",
    "utc_string",
]

#: Public surface grouped by module — handy for docs and quick introspection.
MODULE_MAP: Dict[str, List[str]] = {
    "kmcs.core.exceptions": [name for name in __all__ if name in globals() and "Error" in name or name in {"ErrorCode", "ErrorSeverity", "ErrorContext", "redact", "format_exception"}],
    "kmcs.core.config": ["KmcsConfig", "ConfigManager"],
    "kmcs.core.events": ["EventType", "Record", "EventBus", "AsyncEventBus"],
    "kmcs.core.jobs": ["JobState", "JobDefinition", "JobResult", "JobPlan", "RetryPolicy", "Executor"],
    "kmcs.core.models": ["Target", "Corpus", "Crash", "Finding", "ReportRequest", "Severity"],
}

CORE_VERSION = "1.0.0"
